### ISSUE TITLE
Switch to system-ui font family

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Development#109]
Switch to  system-ui font family, which is native font stack that selects the best font-family for each OS and device
Benefits:
- zero latency and flickering or layout shift
- better performance
- doesn’t require a web-font delivery service

**Comment by extinah** [comment]
Hi Kon - the change in typography affects the template a lot. The direction is good...but there's font size and spacing issues would need to be researched and addressed before implemented. We would want to talk about this as a team.

I know the design system is talking about going in this direction and how to address the the varying fonts.

This is a great idea but it requires a lot of work.

I don't think we have the capacity/resources to dive into this at this point. But the design system is a better place to explore this.

Or we can use this as a sandbox for the design system team but not move forward. Let's chat.
