### ISSUE TITLE
Remove dropdown button generation functionality from navigation.js

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Development#36]
Currently navigation.js generates dropdown menu button if navigation structure has a sub navigation. We need to remove that functionality and instead of generating button via JS we need to use actual button directly in the navigation.njk source code.

**Comment by carterm** [comment]
If we do this we will need to have users place a button in their menus.  That's a breaking change to the markup.  Let's discuss the issue.

**Comment by kkoryaka** [comment]
Adding a tag without href is making the trick.
