### ISSUE TITLE
mobile-controls.js getAllBodyLinks() clears all tabindex values

### ISSUE THREAD

**Issue by carterm** [Office-of-Digital-Services/California-State-Web-Template-Development#43]
mobile-controls.js line 116.  getAllBodyLinks() is a VERY large search that includes most controls on the page..."  // all focusable elements other than navigation".  

The tabindex values are cleared for everything.  

We probably don't want that.

**Comment by kkoryaka** [comment]
@lakey8085CDT this is now updated in dev. Please test on form elements page

**Comment by carterm** [comment]
Fixed in 6.3.1
