### ISSUE TITLE
State CDN files missing

### ISSUE THREAD

**Issue by gocrusade** [Office-of-Digital-Services/California-State-Web-Template-Development#67]
From your State CDN page here: https://template.webstandards.ca.gov/cdn.html, I can't seem to load any of the 'font-only' CSS files AFTER 6.0.7. 

6.0.7 works: 
https://california.azureedge.net/cdt/statetemplate/6.0.7/css/cagov.font-only.min.css

But these do not:
https://california.azureedge.net/cdt/statetemplate/6.0.8/css/cagov.font-only.min.css
https://california.azureedge.net/cdt/statetemplate/6.2.0/css/cagov.font-only.min.css

**Comment by kkoryaka** [comment]
We stopped publishing those CDNs since we switched from GULP generation to eleventy sass and state template didn't require that isolated icon font css file anymore. Is there specific need for the icon font css CDN file in your case?

**Comment by carterm** [comment]
Thank you @gocrusade for noticing that we still had the font-only files listed in the CDN page.  The references have now been removed from the page beyond 6.0.7.
