### ISSUE TITLE
Add actual utility links into utility header

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Development#93]
Add real utility links into utility header. 

<img width="1027" alt="Screenshot 2023-11-14 at 8 48 43 AM" src="https://github.com/Office-of-Digital-Services/California-State-Web-Template-Development/assets/31669748/aec31a6e-ccd8-4660-8c85-897f57b642c1">
<img width="510" alt="Screenshot 2023-11-14 at 8 49 00 AM" src="https://github.com/Office-of-Digital-Services/California-State-Web-Template-Development/assets/31669748/0bd1e2c1-a73c-4f7d-9523-7f9b1f04ed96">

**Comment by kkoryaka** [comment]
@extinah Art waned to add actual utility links into the header since CAWeb and other departments use those links heavily. Would you mind to add them into the figma starter site?

**Comment by extinah** [comment]
> @extinah Art waned to add actual utility links into the header since CAWeb and other departments use those links heavily. Would you mind to add them into the figma starter site?

Will do!

**Comment by kkoryaka** [comment]
After it's updated in figma next step is to add it to template website here:

**Comment by kkoryaka** [comment]
@extinah actual utility links are on the dev website please review and will be added to starter site once we publish 6.3.1: 
https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/structure/utility-header.html

**Comment by extinah** [comment]
Sounds good. Sorry for the delay. Did you just add "Optional utility header links"? That looks good.

In the figma file, we have a utility header links example (it says Application login).

Check it out in the UI kit on the header and starter site boards.

https://www.figma.com/community/file/1296266765771316349

![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Development/assets/33840424/a67c5e84-372e-412f-8a4a-f34a57d6f912)
