### ISSUE TITLE
Make sure that breadcrumbs slashes are visible in dark sections

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Development#95]
breadcrumbs slashes are not visible in dark section such as standout, primary., overstated or impact.
<img width="936" alt="Screenshot 2023-12-27 at 12 17 04 PM" src="https://github.com/Office-of-Digital-Services/California-State-Web-Template-Development/assets/31669748/a49e9a95-410a-4066-a7b4-ce4436d523b5">

**Comment by kkoryaka** [comment]
@extinah this is part of the 6.3.1 here is screenshot of the fixed slash
<img width="635" alt="Screenshot 2024-02-02 at 3 14 58 PM" src="https://github.com/Office-of-Digital-Services/California-State-Web-Template-Development/assets/31669748/4882225c-c678-45e8-b1c9-d96cbcf409e0">

**Comment by extinah** [comment]
This is great. Thank you.
